apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-source-to-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-source-to-app
rules:
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - "*"
- apiGroups:
  - tekton
  resources:
  - pipelineruns
  verbs:
  - "*"
# ToDo needs rights for tekton 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-source-to-app-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: github-source-to-app
subjects:
- kind: ServiceAccount
  name: github-source-to-app
  namespace: default
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: github-source-to-app-service
spec:
  template:
    containers:
      spec:
        serviceAccountName: github-source-to-app
        container:
          image: johscheuer/github-source-to-app:latest
