apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: github-build-trigger
spec:
  filter:
    sourceAndType:
      type: dev.knative.source.github.push
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: github-source-to-app-service
