apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-event-listener
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-event-listener
rules:
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-event-listener-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: github-event-listener
subjects:
- kind: ServiceAccount
  name: github-event-listener
  namespace: default
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: github-source-to-app-service
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          labels:
            knative.dev/type: app
        spec:
          serviceAccountName: github-event-listener
          container:
            image: johscheuer/event-trigger-github:latest
